lib/bookshelf_web/router.ex
defmodule BookshelfWeb.Router do
  use BookshelfWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.AccountSession
  end

  pipeline :admin_browser do
    plug :put_layout, {BookshelfWeb.LayoutView, "admin.html"}
    plug BasicAuth, use_config: {:bookshelf, BookshelfWeb.Admin}
  end

  scope "/", BookshelfWeb do
    pipe_through :browser

    get "/", PageController, :index
    post "/signup", PageController, :signup
    get "/u/:username", BookListController, :index

    scope "/profile" do
      get "/", ProfileController, :show
      post "/login", ProfileController, :auth
      post "/", ProfileController, :update
      get "/logout", ProfileController, :logout
    end
  end

  scope "/~/admin", BookshelfWeb do
    pipe_through :browser
    pipe_through :admin_browser

    resources "/accounts", AccountController
  end
end

lib/bookshelf_web/templates/page/index.html.eex
<div class="lg:flex justify-center">
  <div class="lg:w-1/2 px-6 mt-32">

    <div class="mb-8">
      <h1 class="text-4xl font-bold">
        Bookshelf
      </h1>

      <small class="text-lg font-light">
        See what everyone's reading, simply.
      </small>
    </div>

    <%= render BookshelfWeb.LayoutView, "flash.html", assigns %>

    <div class="x l:w-2/3 bg-white border rounded p-4 mt-8">
    <%= form_for @changeset, Routes.page_path(@conn, :signup), fn f -> %>
      <h2 class="font-bold mb-3">
        Get started
      </h2>

      <div class="mb-3">
        <%= text_input f, :username, placeholder: "A username", class: "border rounded px-4 py-1 w-full" %>
        <span class="text-red-500">
          <%= error_tag f, :username %>
        </span>
      </div>

      <div class="mb-6">
        <%= text_input f, :name, placeholder: "Your first name", class: "border rounded px-4 py-1 w-full" %>
        <span class="text-red-500">
          <%= error_tag f, :name %>
        </span>
      </div>

      <div class="mb-3">
        <span>Copy</span>
        <a class="text-blue-500 underline" href="<%= @base_template %>" target="_blank" rel="noopener noreferrer">
          this Airtable base</a><span>, and fill out:</span>
      </div>

      <div class="mb-3">
        <%= password_input f, :airtable_api_key, placeholder: "Airtable API key", class: "border rounded px-4 py-1 w-full" %>
        <span class="text-red-500">
          <%= error_tag f, :airtable_api_key %>
        </span>
      </div>

      <div class="mb-6">
        <%= text_input f, :airtable_base, placeholder: "Airtable base ID", class: "border rounded px-4 py-1 w-full" %>
        <span class="text-red-500">
          <%= error_tag f, :airtable_base %>
        </span>
      </div>

      <%= submit "Sign up", class: "border-0 rounded bg-blue-500 text-white px-4 py-2" %>

      <a href="<%= Routes.profile_path(@conn, :show) %>">
        <button type="button" class="border border-black rounded bg-white text-black px-4 py-2 ml-2">
          Sign in
        </button>
      </a>
    <% end %>
    </div>
  </div>
</div>